### PR TITLE
Compile with or without classes

### PR DESCRIPTION
**Pull request by Jaspur**
Something like this. What do you think? Would be nice I think. Now people can include the hover.scss file, and compile it without all the classes, and still use the @include for adding an effect.

Don't know if it's correct for Less.

### CODE REVIEW

**Comment by IanLunn** [comment]
Ok cool. A few others on Twitter (including you :wink: ) have shown interest for this as well. Happy to add it. Will test soon then merge.

**Comment by Jaspur** [comment]
Regarding commit 20cd280 :
 http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_ 

Because of the ```!default``` added to the variables, you can overwrite them. And do something like this:
```
$nameSpace: 'overwritten-namespace';
$secondaryColor: pink;
$include-classes: false;
@import "../bower/Hover/scss/hover";
```

**Comment by Jaspur** [comment]
:+1: So the less-version also worked? Nice.

**Comment by IanLunn** [comment]
Had to change the equal operator from `==` to `=`. I'm not so familiar with LESS so hopefully that is correct but the preprocesser was happy with it. Thanks for the inclusion of `!default` as well, wasn't aware of that.

**Comment by IanLunn** [comment]
Only one issue I see with this update, it works, *but* the keyframes still get generated in `hover.css` so I believe you will still need to include a reference to that.

**Comment by Jaspur** [comment]
Oke, I'll check it someday this week.Thanks for merging.

**Comment by Jaspur** [comment]
I found out that the Keyframes are always needed. 

Current use-case what I intended is now:
```
$includeClasses: false;
@import  "../bower/Hover/scss/hover";
header figure{ 
	border: none; 
	&:hover{
		@include grow();
	}
}
```
People can include the mixin-name of the effect. And optionally create their own classes.

**Pull request merged**
