### PR TITLE
Add back pulse animation

### PR DESCRIPTION
**Pull request by Dusandinho**
Hi there,

I'm new here but I'm interested in what you're doing and thought I could add a little bit to it. Let me know what you think, it's a pulse animation but to the background instead of the growing and shrinking pulse that you already have.

### CODE REVIEW

**Comment by IanLunn** [comment]
Hi @Dusandinho, great job! Will definitely add this in the next update.

**Comment by Dusandinho** [comment]
Happy to help!

**Comment by spartain336** [comment]
Thank u

**Comment by IanLunn** [comment]
It's in 2.0.2. Thanks!

**Pull request merged**
