### PR TITLE
Add spm support

### PR DESCRIPTION
**Pull request by afc163**
A nicer package manager: http://spmjs.io
Documentation: http://spmjs.io/documentation

http://spmjs.io/package/hover.css

---

It is a browser-side package manager popular in China, suppling a complete lifecycle managment of package via [spm](https://github.com/spmjs/spm/tree/master).

> If you need ownership of hover.css in spmjs, I can add it for your account after signing in http://spmjs.io.

spmjs/spm#781

### CODE REVIEW

**Comment by IanLunn** [comment]
Any +1s on this? Not heard of SPM myself.

**Comment by yolo2013** [comment]
@IanLunn SPM -> SeaJS Package Manage. And [Sea.js](https://github.com/seajs/seajs) is a popular module loader lib(like requirejs) in China.

**Comment by afc163** [comment]
spm is `Static package maneger`, not `SeaJS Package Manage`.

**Comment by afc163** [comment]
ping~

**Pull request closed without merging**
