### PR TITLE
Alphabetization of properties

### PR DESCRIPTION
**Pull request by awelch83**
I've alphabetized properties for all classes in hover.css and demo-page.css. I've also updated hover-min to reflect the changes that I made to hover.css.

### CODE REVIEW

**Comment by renege** [comment]
Wtf

**Comment by IanLunn** [comment]
Thanks for your work @awelch83 but I don't think this improves the project -- not everybody writes their properties in alphabetical order (I personally don't). It also means additional work to apply the same to the Sass and LESS formats.

**Comment by awelch83** [comment]
It improves the project by making it more readable for future contributors. That's how. See below:

https://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml#CSS_Style_Rules

That was a nice 1+ hours wasted. Thanks for the warm welcome. I have no desire to be involved with this project anymore.

**Comment by IanLunn** [comment]
Sorry you feel that way @awelch83. I appreciate your work and I'm sure you haven't wasted your time as no doubt others will like the library formatted in this way too. I will be sure to point them to your pull request. Of course, if lots of people request this, I will reconsider but for now my reason for not merging is because alphabetization isn't a standard. Not everybody works in this way.

**Comment by renege** [comment]
@awelch83  http://css-tricks.com/poll-results-how-do-you-order-your-css-properties/

**Pull request closed without merging**
